spring:
  profiles:
    active: local
    group:
      local:
        - common
      prod:
        - common
---
spring:
  config:
    activate:
      on-profile: common
jwt:
  token:
    expired-time-ms: 61200000000
    secret-key: ajoumc-wjdqhcjwlxla-dhvlvkdlf-ghkddlsrbaksema
server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/op
    username: root
    password: ajoumc1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false